<a href="https://colab.research.google.com/github/WooyeongJang/ml-with-pytorch/blob/main/3%EC%A3%BC%EC%B0%A8_%EC%8B%A4%EC%8A%B5_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from io import StringIO
csv_data = '''
A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,
'''
df = pd.read_csv(StringIO(csv_data))
df

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [2]:
# 열별로 결측의 수 확인열별로 결측의 수 확인
df.isnull().sum()
# df.isnull().sum(axis=1)

A    0
B    0
C    1
D    1
dtype: int64

In [3]:
# pandas dataframe에서 numpy 배열을 얻을 수 있음
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

In [4]:
import pandas as pd
import numpy as np

print("=== 1. 데이터 생성 ===")
df = pd.DataFrame({
    'A': [1, np.nan, 3],
    'B': [1, None, 3],
    'C': [1, pd.NA, 3],
    'D': ["a", "Na", None]  # "Na"는 문자열 (결측 아님)
})
print(df)

=== 1. 데이터 생성 ===
     A    B     C     D
0  1.0  1.0     1     a
1  NaN  NaN  <NA>    Na
2  3.0  3.0     3  None

In [5]:
print("=== 2. 결측값 확인 ===")
print(df.isnull())
print("\n=== 3. 열별 결측 개수 (axis=0) ===")
print(df.isnull().sum())
print("\n=== 4. 행별 결측 개수 (axis=1) ===")
print(df.isnull().sum(axis=1))
print("\n=== 5. NaN vs pd.NA 비교 ===")
print("np.nan == np.nan:", np.nan == np.nan)
print("pd.NA == pd.NA:", pd.NA == pd.NA)
print("\n=== 6. 문자열 'Na'는 결측인가? ===")
print("pd.isnull('Na'):", pd.isnull("Na"))

=== 2. 결측값 확인 ===
       A      B      C      D
0  False  False  False  False
1   True   True   True  False
2  False  False  False   True

=== 3. 열별 결측 개수 (axis=0) ===
A    1
B    1
C    1
D    1
dtype: int64

=== 4. 행별 결측 개수 (axis=1) ===
0    0
1    3
2    1
dtype: int64

=== 5. NaN vs pd.NA 비교 ===
np.nan == np.nan: False
pd.NA == pd.NA: <NA>

=== 6. 문자열 'Na'는 결측인가? ===
pd.isnull('Na'): False

In [6]:
# 4.1.2 누락된 값이 있는 훈련 샘플이나 특성 제외
import pandas as pd
from io import StringIO
csv_data = '''
A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,
'''
df = pd.read_csv(StringIO(csv_data))
df

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [7]:
df.dropna(axis=0)

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [8]:
df.dropna(axis=1)

      A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

In [9]:
df.dropna(how='all')

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [10]:
df.dropna(thresh=4)

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [11]:
df.dropna(subset=['C'])

      A     B     C    D
0   1.0   2.0   3.0  4.0
2  10.0  11.0  12.0  NaN

In [12]:
from sklearn.impute import SimpleImputer
import numpy as np
imr = SimpleImputer(missing_values=np.nan, strategy='mean')
imr = imr.fit(df.values)

In [13]:
imputed_data = imr.transform(df.values)
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

In [14]:
# median
imr_median = SimpleImputer(missing_values=np.nan, strategy='median')
imr_median = imr.fit(df.values)
imputed_data_median = imr_median.transform(df.values)
# most_frequent
imr_most_frequent = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imr_most_frequent = imr_most_frequent.fit(df.values)
imputed_data_median_most_frequent = imr_most_frequent.transform(df.values)
# constant
imr_constant = SimpleImputer(missing_values=np.nan, strategy='constant')
imr_constant = imr.fit(df.values)
imputed_data_median_constant = imr_constant.transform(df.values)

In [15]:
print(imputed_data_median)
print(imputed_data_median_most_frequent)
print(imputed_data_median_constant)

[[ 1.   2.   3.   4. ]
 [ 5.   6.   7.5  8. ]
 [10.  11.  12.   6. ]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  3.  8.]
 [10. 11. 12.  4.]]
[[ 1.   2.   3.   4. ]
 [ 5.   6.   7.5  8. ]
 [10.  11.  12.   6. ]]

In [16]:
from sklearn.preprocessing import FunctionTransformer
ftr_imr = FunctionTransformer(lambda X: imr.fit_transform(X.T).T, validate=False)
imported_data = ftr_imr.fit_transform(df.values)
imported_data

array([[ 1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        ,  6.33333333,  8.        ],
       [10.        , 11.        , 12.        , 11.        ]])

In [17]:
from sklearn.preprocessing import FunctionTransformer

# 1. 함수 정의 (lambda 대신)
def impute_rowwise(X):
    # 행 기준 처리를 위해 전치 → imputer 적용 → 다시 전치
    return imr.fit_transform(X.T).T

# 2. FunctionTransformer에 함수 전달
ftr_imr = FunctionTransformer(impute_rowwise, validate=False)
# 3. 데이터 적용
imported_data = ftr_imr.fit_transform(df.values)
# 4. 결과 출력
print(imported_data)

[[ 1.          2.          3.          4.        ]
 [ 5.          6.          6.33333333  8.        ]
 [10.         11.         12.         11.        ]]

In [52]:
# 4.2.1
import pandas as pd

df = pd.DataFrame([['green', 'M', 10.1, 'class2'],
                   ['red', 'L', 13.5, 'class1'],
                   ['blue', 'XL', 15.3, 'class2']])

df.columns = ['color', 'size', 'price', 'classlabel']
df

   color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

In [19]:
# 4.2.2 순서가 있는 특성 매핑
# XL = L +1 = M + 2
size_mapping = {'XL': 3,
                'L': 2,
                'M': 1}

df['size'] = df['size'].map(size_mapping)
df

   color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2

In [20]:
inv_size_mapping = {v: k for k, v in size_mapping.items()}
df['size'].map(inv_size_mapping)

0     M
1     L
2    XL
Name: size, dtype: object

In [21]:
# 4.2.3 클래스 레이블 인코딩
# 1. 클래스 라벨 가져오기
labels = df['classlabel']
# 2. 중복 제거 (고유값만 추출)
unique_labels = list(set(labels))
# 3. 정렬 (순서 고정)
unique_labels.sort()
# 4. 빈 딕셔너리 만들기
class_mapping = {}
# 5. 하나씩 숫자 붙이기
idx = 0
for label in unique_labels:
    class_mapping[label] = idx
    idx += 1
# 결과
print(class_mapping)

{'class1': 0, 'class2': 1}

In [22]:
# 4.2.3 클래스 레이블 인코딩
import numpy as np
class_mapping = {label:idx for idx, label in enumerate(np.unique(df['classlabel']))}
class_mapping

{'class1': 0, 'class2': 1}

In [23]:
from sklearn.preprocessing import LabelEncoder

# 사이킷런의 LabelEncoder을 사용한 레이블 인코딩
class_le = LabelEncoder()
y = class_le.fit_transform(df['classlabel'].values)
y

array([1, 0, 1])

In [24]:
# 거꾸로 매핑
class_le.inverse_transform(y)

array(['class2', 'class1', 'class2'], dtype=object)

In [25]:
# 클래스 레이블을 문자열에서 정수로 바꿉니다
df['classlabel'] = df['classlabel'].map(class_mapping)
df

   color  size  price  classlabel
0  green     1   10.1           1
1    red     2   13.5           0
2   blue     3   15.3           1

In [26]:
# 클래스 레이블을 거꾸로 매핑합니다
inv_class_mapping = {v: k for k, v in class_mapping.items()}
df['classlabel'] = df['classlabel'].map(inv_class_mapping)
df

   color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2

In [40]:
# 4.2.4
X = df[['color', 'size', 'price']].values
print(X)
color_le = LabelEncoder()
X[:, 0] = color_le.fit_transform(X[:, 0])
print(X)

[['green' 1 10.1]
 ['red' 2 13.5]
 ['blue' 3 15.3]]
[[1 1 10.1]
 [2 2 13.5]
 [0 3 15.3]]

In [41]:
X[:,:]

array([[1, 1, 10.1],
       [2, 2, 13.5],
       [0, 3, 15.3]], dtype=object)

In [42]:
df.values

array([['green', 1, 10.1, 'class2'],
       ['red', 2, 13.5, 'class1'],
       ['blue', 3, 15.3, 'class2']], dtype=object)

In [43]:
from sklearn.preprocessing import OneHotEncoder

X = df[['color']]

ohe = OneHotEncoder()
ohe.fit_transform(X).toarray()

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [64]:
from sklearn.preprocessing import OneHotEncoder

X = df[['color']]

ohe = OneHotEncoder(drop='first')
ohe.fit_transform(X).toarray()

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [46]:
from sklearn.compose import ColumnTransformer

X = df[['color', 'size', 'price']].values
c_transf = ColumnTransformer([ ('onehot', OneHotEncoder(), [0]),
                               ('nothing', 'passthrough', [1, 2])])
c_transf.fit_transform(X).astype(float)

array([[ 0. ,  1. ,  0. ,  1. , 10.1],
       [ 0. ,  0. ,  1. ,  2. , 13.5],
       [ 1. ,  0. ,  0. ,  3. , 15.3]])

In [57]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# ColumnTransformer 설정
ct = ColumnTransformer(
    transformers=[
        # color 컬럼만 원핫 인코딩
        ('onehot', OneHotEncoder(), ['color'])
    ],

    # 핵심: 나머지 컬럼(size, price)은 그대로 유지
    remainder='passthrough'
)
# 변환 실행
result = ct.fit_transform(df)
# 결과 출력
print(result)

[[0.0 1.0 0.0 'M' 10.1 'class2']
 [0.0 0.0 1.0 'L' 13.5 'class1']
 [1.0 0.0 0.0 'XL' 15.3 'class2']]

In [62]:
import pandas as pd
pd.get_dummies(df[['price','color','size']], columns=['color'])

   price size  color_blue  color_green  color_red
0   10.1    M       False         True      False
1   13.5    L       False        False       True
2   15.3   XL        True        False      False

In [69]:
# 4.3
df_wine = pd.read_csv('https://archive.ics.uci.edu/'
                      'ml/machine-learning-databases/wine/wine.data',
                      header=None)

df_wine.columns = ['Class label', 'Alcohol', 'Malic acid', 'Ash',
                   'Alcalinity of ash', 'Magnesium', 'Total phenols',
                   'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins',
                   'Color intensity', 'Hue', 'OD280/OD315 of diluted wines',
                   'Proline']

print('Class labels', np.unique(df_wine['Class label']))
df_wine.head()

Class labels [1 2 3]

,Class label,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [67]:
from sklearn.model_selection import train_test_split

X, y = df_wine.iloc[:, 1:].values, df_wine.iloc[:, 0].values

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=0,
    stratify=y
    )

In [72]:
#4.4
from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()

X_train_norm = mms.fit_transform(X_train)
X_test_norm = mms.transform(X_test)

In [ ]:
# 스케일러 생성
mms = MinMaxScaler()
# 학습 (train 데이터로 기준 만들기)
mms.fit(X_train)

# 여기서 내부적으로 min, max 저장됨

# train 변환
X_train_norm = mms.transform(X_train)
# test 변환 (같은 기준 사용)
X_test_norm = mms.transform(X_test)

In [75]:
#4.5
import pandas as pd
from sklearn.linear_model import LogisticRegression
# 샘플 데이터 (컬럼 3개)
X = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [2, 4, 6, 8, 10],   # A와 거의 같은 정보 (불필요 가능성)
    'C': [5, 3, 6, 2, 1]
})

# 타겟
y = [0, 0, 1, 1, 1]
# L1 규제 모델 생성
model = LogisticRegression(penalty='l1', solver='liblinear')
# 학습
model.fit(X, y)
# 각 컬럼의 중요도 (계수)
coef = model.coef_[0]
print("각 feature의 계수:", coef)
# 0이 아닌 컬럼만 선택 (feature selection)
selected_features = X.columns[coef != 0]
print("선택된 feature:", selected_features)

각 feature의 계수: [ 0.          0.27852569 -0.21045807]
선택된 feature: Index(['B', 'C'], dtype='object')

In [76]:
from sklearn.linear_model import LogisticRegression
# L2 규제 모델
model = LogisticRegression(penalty='l2')
# 학습
model.fit(X, y)
coef = model.coef_[0]
print("각 feature의 계수:", coef)

각 feature의 계수: [0.41550362 0.83100723 0.29350313]

In [78]:
#4.6
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

# 데이터 생성
X = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [2, 4, 6, 8, 10],   # A와 거의 동일 (중복 정보)
    'C': [5, 3, 6, 2, 1]
})

y = [0, 0, 1, 1, 1]


# 랜덤포레스트 모델 생성
model = RandomForestClassifier(random_state=0)

# 학습
model.fit(X, y)

# feature 중요도 확인
importances = model.feature_importances_

# 보기 쉽게 출력
for col, val in zip(X.columns, importances):
    print(col, ":", val)

A : 0.35683760683760685
B : 0.4508547008547008
C : 0.19230769230769226

In [80]:
import numpy as np
# 기준 설정 (예: 0.2 이상만 선택)
threshold = 0.2
selected_features = X.columns[importances > threshold]
print("선택된 feature:", selected_features)

선택된 feature: Index(['A', 'B'], dtype='object')